config/routes.rb
Blog::Application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users

  root to: 'posts#index', via: :get

  resources :posts, only: [:show, :index] do
    resources :comments, only: [:create, :destroy]
  end

  get 'categories/:category', to: 'posts#index', as: :category
  get 'author/:author',       to: 'posts#index', as: :user
  get 'tags/:tag',            to: 'posts#index', as: :tag

  authenticate :user do
    namespace :admin do
      root to: 'dashboard#show'
      resources :users do
        post :recover, on: :member
      end
      resources :posts, except: :show
      resources :categories, except: :show
    end
  end

end

app/helpers/navigation_helper.rb
module NavigationHelper
  def path_active(path)
    yield path, path_active?(path)
  end

  def path_active?(path)
    @breadcrumbs.any? do |breadcrumb|
      breadcrumb_path = breadcrumb.path
      breadcrumb_path =  send(breadcrumb_path) if breadcrumb_path.is_a? Symbol
      breadcrumb_path == path
    end
  end

  def path_active_class(path)
    path ? :active : nil
  end

  def paginate(colleciton)
    will_paginate colleciton, renderer: BootstrapPagination::Rails
  end
end

app/views/layouts/admin/navigation/_sidebar.html.haml
-if can? :manage, :users
  %ul.nav.nav-sidebar.nav-pills.nav-stacked
    - path_active admin_users_path do |path, active|
      =content_tag :li, class: path_active_class(active) do
        =link_to icon(:users, 'Users'), path

-if can? :manage, :posts
  %ul.nav.nav-sidebar.nav-pills.nav-stacked
    - path_active admin_posts_path do |path, active|
      =content_tag :li, class: path_active_class(active) do
        =link_to icon(:'file-text-o', 'Posts'), path

-if can? :manage, :categories
  %ul.nav.nav-sidebar.nav-pills.nav-stacked
    - path_active admin_categories_path do |path, active|
      =content_tag :li, class: path_active_class(active) do
        =link_to icon(:'folder-open-o', 'Categories'), path

app/views/layouts/admin/navigation/_top.html.haml
/ Fixed navbar
.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to icon(:home, 'homepage'), root_path
        = render partial: 'shared/navigation/auth'
    / /.nav-collapse